### ISSUE TITLE
accessory configuration/removal error after adjusting refresh interval and restarting Homebridge

### ISSUE THREAD

**Issue by beckbg** [RMCob/homebridge-wyze-connected-home-op#33]
Could very well be a stupid user error, but:  I adjusted the Refresh Interval in the plugin settings, hit save, and restarted homebridge and now am in an endless loop as follows:

```
[5/31/2022, 12:04:11 PM] Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (C:\ProgramData\npmglobal\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:640:13)
    at Bridge.Accessory.removeBridgedAccessories (C:\ProgramData\npmglobal\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:654:12)
    at BridgeService.handleUnregisterPlatformAccessories (C:\ProgramData\npmglobal\node_modules\homebridge\src\bridgeService.ts:404:17)
    at HomebridgeAPI.emit (node:events:527:28)
    at HomebridgeAPI.unregisterPlatformAccessories (C:\ProgramData\npmglobal\node_modules\homebridge\src\api.ts:355:10)
    at WyzeConnectedHome.configureAccessory (C:\ProgramData\npmglobal\node_modules\homebridge-wyze-connected-home-op\src\WyzeConnectedHome.js:159:16)
    at C:\ProgramData\npmglobal\node_modules\homebridge\src\bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (C:\ProgramData\npmglobal\node_modules\homebridge\src\bridgeService.ts:288:69)
    at Server.start (C:\ProgramData\npmglobal\node_modules\homebridge\src\server.ts:173:24)
[5/31/2022, 12:04:11 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[5/31/2022, 12:04:16 PM] [HB Supervisor] Restarting Homebridge...
```

**Comment by beckbg** [comment]
Disabled it, enabled it as child bridge, haven’t seen the error again yet, but we’ll see. Several things acting weird with my Homebridge so probably a setup mistake on my part, whether with this plugin or another.

**Comment by beckbg** [comment]
Just kidding, failed again. Brain’s too foggy, uninstalled for now and might try again tomorrow or wait until I’ve fixed the other Homebridge problem—waiting is probably wiser.
